#!/usr/bin/env ansible-playbook
---

- import_playbook: playbooks/root.yml
- import_playbook: playbooks/upgrade.yml
- import_playbook: playbooks/ferm.yml
- import_playbook: playbooks/backup.yml
- import_playbook: playbooks/postfix-relay.yml
- import_playbook: playbooks/netdata.yml
- import_playbook: playbooks/postgres.yml
- import_playbook: playbooks/mariadb.yml
- import_playbook: playbooks/redis.yml
- import_playbook: playbooks/rspamd.yml
- import_playbook: playbooks/certbot-ovh.yml
- import_playbook: playbooks/postfix.yml
- import_playbook: playbooks/dovecot.yml
- import_playbook: playbooks/nextcloud.yml
- import_playbook: playbooks/wallabag.yml
- import_playbook: playbooks/gitea.yml
- import_playbook: playbooks/wordpress.yml
- import_playbook: playbooks/nginx.yml
- import_playbook: playbooks/certbot-webroot.yml

...
