---

- name: rebuild sasl_passwd
  command:
    cmd: postmap /etc/postfix/sasl_passwd

- name: rebuild aliases
  command:
    cmd: postalias /etc/aliases

- name: restart relay server
  systemd:
    name: postfix
    state: restarted

...
