---

# SYSTEM

- name: install packages
  notify: restart apache
  apt:
    force_apt_get: true
    install_recommends: false
    name: "{{ wp_packages }}"

# DATABASE

- name: create database
  no_log: true
  register: wp_db_create
  mysql_db:
    login_host: "{{ wp_db_host }}"
    login_port: "{{ wp_db_port }}"
    login_user: "{{ wp_db_admin }}"
    login_password: "{{ wp_db_admin_password }}"
    name: "{{ wp_db_name }}"

- name: create database user
  no_log: true
  mysql_user:
    login_host: "{{ wp_db_host }}"
    login_port: "{{ wp_db_port }}"
    login_user: "{{ wp_db_admin }}"
    login_password: "{{ wp_db_admin_password }}"
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_user_password }}"
    priv: '{{ wp_db_name }}.*:ALL'
    host: "%"

# APPLICATION

- name: download wordpress
  register: wp_download
  get_url:
    url: "{{ wp_url }}"
    dest: "{{ wp_path | dirname }}/wordpress-{{ wp_version }}-fr_FR.tar.gz"

- name: create wordpress directory
  file:
    path: "{{ wp_path }}"
    owner: www-data
    group: www-data
    state: directory

- name: extract wordpress archive
  when: wp_download is changed
  unarchive:
    remote_src: true
    src: "{{ wp_path | dirname }}/wordpress-{{ wp_version }}-fr_FR.tar.gz"
    dest: "{{ wp_path }}"
    group: www-data
    owner: www-data

# APACHE

- name: remove default vhost
  notify: restart apache
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: enable required apache modules
  notify: restart apache
  loop: "{{ wp_apache_mods }}"
  apache2_module:
    name: "{{ item }}"

- meta: flush_handlers

- name: configure vhost
  notify: restart apache
  copy:
    dest: /etc/apache2/sites-available/wordpress.conf
    content: "{{ wp_apache_vhost }}"

- name: enable vhost
  notify: restart apache
  command:
    cmd: a2ensite wordpress.conf
    creates: /etc/apache2/sites-enabled/wordpress.conf

- name: configure remoteip
  when: wp_trusted_proxies | length > 0
  notify: restart apache
  copy:
    dest: /etc/apache2/conf-available/remoteip.conf
    content: "{{ wp_apache_remoteip }}"

- name: enable remoteip
  when: wp_trusted_proxies | length > 0
  notify: restart apache
  command:
    cmd: a2enconf remoteip.conf
    creates: /etc/apache2/conf-enabled/remoteip.conf

...
