---

ferm_antilockout_enabled: false

ferm_input_log: false
ferm_forward_log: false

ferm_input_rule_ssh:
  saddr:
    - "{{ lookup('dig', 'home.karolak.fr') }}"
    - '193.50.159.0/24'
  proto:
    - tcp
  dport:
    - 22
