---

ferm_input_rules:
  - "{{ ferm_input_rule_ssh }}"
  - "{{ ferm_input_rule_netdata }}"
  # lmtp
  - saddr:
      - "{{ lookup('dig', 'smtp.priv.karolak.fr') }}"
    proto:
      - tcp
    dport:
      - 24
  # dovecot-sasl
  - saddr:
      - "{{ lookup('dig', 'smtp.priv.karolak.fr') }}"
    proto:
      - tcp
    dport:
      - 1993
