---

version: "3.8"

services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
    user: "code"
    volumes:
      # workspace
      - "..:/workspace"
      # dotfiles
      - "$HOME/.vimrc:/home/code/.vimrc"
      - "$HOME/.vim/conf.d:/home/code/.vim/conf.d"
      - "$HOME/.gitconfig:/home/code/.gitconfig"
      - "$HOME/.ssh:/home/code/.ssh"
      - "$HOME/.gnupg:/home/code/.gnupg"
    environment:
      - "SSH_AUTH_SOCK=/home/code/.gnupg/S.gpg-agent.ssh"
    env_file:
      - "../ovh.conf"
      - "../scaleway.conf"
