---

bkp_jobs:
  - name: databases
    type: pgsql
  - type: sh
    priority: 20
    name: restic
    command: |
      restic snapshots &> /dev/null || restic init
      restic backup /etc /var/www /var/backups/postgres
      restic forget --prune --keep-daily 7 --keep-weekly 4
