---

relay_packages:
  - libsasl2-modules
  - postfix

relay_hostname: "{{ ansible_hostname }}"
relay_domain: localdomain
relay_destinations:
  - $myhostname
  - "{{ relay_hostname }}.{{ relay_domain }}"
  - "{{ relay_hostname }}"
  - "{{ relay_hostname }}.localdomain"
  - localhost.localdomain
  - localhost
relay_interfaces: all
relay_protocols: all
relay_networks:
  - 127.0.0.0/8
  - "[::ffff:127.0.0.0]/104"
  - "[::1]/128"

relay_host:
relay_user:
relay_password:

relay_admin:

...
