---

pg_packages:
  - postgresql
  - python3-psycopg2

pg_version: 11
pg_cluster: main

pg_password:

pg_conf_dir: /etc/postgresql/{{ pg_version }}/{{ pg_cluster }}

pg_conf:
  - name: main
    content:

pg_hba:
  - type: local
    method: peer
  - type: host
    address: 127.0.0.1/32
  - type: host
    address: ::1/128
  - type: local
    database: replication
    method: peer
  - type: host
    database: replication
    address: 127.0.0.1/32
  - type: host
    database: replication
    address: ::1/128

pg_users: []

pg_databases: []

...
