---

pg_conf:
  - name: global
    content: |
      listen_addresses = '*'

pg_hba:
  - type: local
    method: peer
  - type: host
    address: 127.0.0.1/32
  - type: host
    address: ::1/128
  - type: host
    address: 0.0.0.0/0
  - type: host
    address: ::/0

pg_password: "{{ vault_pg_password }}"
