---

grocy_domain: 'grocy.karolak.fr'
grocy_features:
  stock: true
  shoppinglist: true
  recipes: true
  chores: true
  tasks: false
  batteries: false
  equipment: false
  calendar: false
grocy_trusted_proxies:
  - '{{ lookup("dig", "lb.priv.karolak.fr") }}'
grocy_settings:
  lang: 'fr'
  currency: 'EUR'
