---

bkp_jobs:
  - name: databases
    type: pgsql
  - type: sh
    priority: 20
    name: restic
    command: |
      restic snapshots &> /dev/null || restic init
      restic backup \
        /etc \
        /var/backups/postgres \
        /var/run/rss2email \
        /var/www/grocy \
        /var/www/nextcloud \
        /var/www/nextcloud-data \
        /var/www/roundcubemail \
        /var/www/wallabag
      restic forget --prune --keep-daily 7 --keep-weekly 4
