---

php_ansible_requirements:
  - gnupg

php_version: 7.4

php_repository_key: https://packages.sury.org/php/apt.gpg
php_repository: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main

php_packages:
  - php{{ php_version }}-fpm

php_users: []

php_pools: []
