---

bkp_jobs:
  - name: restic
    priority: 20
    type: sh
    command: |
      restic snapshots &> /dev/null || restic init
      restic backup /etc /var/www
      restic forget --prune --keep-daily 7 --keep-weekly 4
